# Generated by Django 3.1.6 on 2021-02-01 14:18

import cheep_api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Codeplug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_filename', models.CharField(max_length=128)),
                ('for_radio', models.CharField(max_length=128)),
                ('sizebytes', models.PositiveIntegerField()),
                ('contents', models.FileField(upload_to=cheep_api.models.user_storage)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
