# Generated by Django 3.1.6 on 2021-02-27 03:12

import cheep_api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheep_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RadioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('aliases', models.CharField(max_length=256)),
                ('manufacturer', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_filename', models.CharField(max_length=128)),
                ('for_radios', models.CharField(max_length=128)),
                ('sizebytes', models.PositiveIntegerField()),
                ('contents', models.FileField(upload_to=cheep_api.models.firmware_storage)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
