# Generated by Django 3.1.6 on 2021-02-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheep_api', '0002_firmware_radiomanufacturer_radiomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='codeplug',
            name='for_radio',
        ),
        migrations.AddField(
            model_name='codeplug',
            name='for_radio',
            field=models.ManyToManyField(to='cheep_api.RadioModel'),
        ),
        migrations.AddField(
            model_name='codeplug',
            name='tags',
            field=models.ManyToManyField(to='cheep_api.Tags'),
        ),
        migrations.AddField(
            model_name='firmware',
            name='tags',
            field=models.ManyToManyField(to='cheep_api.Tags'),
        ),
    ]
