# Generated by Django 3.1.6 on 2021-02-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheep_api', '0004_auto_20210227_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='distribution',
            field=models.CharField(default='OEM', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='firmware',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firmware',
            name='version',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='radiomanufacturer',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
