# Generated by Django 3.1.6 on 2021-02-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheep_api', '0005_auto_20210227_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='orig_filename',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
