# Generated by Django 3.1.7 on 2021-12-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheep_api', '0008_auto_20211201_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeplug',
            old_name='orig_filename',
            new_name='filename',
        ),
    ]
