# Generated by Django 3.1.7 on 2021-12-01 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cheep_api', '0009_auto_20211201_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
