# Generated by Django 3.1.8 on 2021-12-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheep_api', '0010_firmware_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='filename',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='sha256hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
